[colors.primary]
background = "#faede8"
foreground = "#2c001e"
dim_foreground = "#2c001e"
bright_foreground = "#2c001e"

[colors.cursor]
text = "#faede8"
cursor = "#2c001e"

[colors.vi_mode_cursor]
text = "#faede8"
cursor = "#2c001e"

[colors.search.matches]
foreground = "#faede8"
background = "#e95420"

[colors.search.focused_match]
foreground = "#2c001e"
background = "#e6b29b"

[colors.footer_bar]
foreground = "#2c001e"
background = "#e6b29b"

[colors.selection]
text = "#faede8"
background = "#e95420"

[colors.normal]
black = "#2c001e"
red = "#2c001e"
green = "#2c001e"
yellow = "#2c001e"
blue = "#2c001e"
magenta = "#2c001e"
cyan = "#2c001e"
white = "#2c001e"

[colors.bright]
black = "#2c001e"
red = "#2c001e"
green = "#2c001e"
yellow = "#2c001e"
blue = "#2c001e"
magenta = "#2c001e"
cyan = "#2c001e"
white = "#2c001e"

[colors.dim]
black = "#2c001e"
red = "#2c001e"
green = "#2c001e"
yellow = "#2c001e"
blue = "#2c001e"
magenta = "#2c001e"
cyan = "#2c001e"
white = "#2c001e"
