[colors.primary]
background = "#faede8"
foreground = "#3a0f12"
dim_foreground = "#3a0f12"
bright_foreground = "#3a0f12"

[colors.cursor]
text = "#faede8"
cursor = "#3a0f12"

[colors.vi_mode_cursor]
text = "#faede8"
cursor = "#3a0f12"

[colors.search.matches]
foreground = "#faede8"
background = "#c73a2a"

[colors.search.focused_match]
foreground = "#3a0f12"
background = "#e3a19a"

[colors.footer_bar]
foreground = "#3a0f12"
background = "#e3a19a"

[colors.selection]
text = "#faede8"
background = "#c73a2a"

[colors.normal]
black = "#3a0f12"
red = "#3a0f12"
green = "#3a0f12"
yellow = "#3a0f12"
blue = "#3a0f12"
magenta = "#3a0f12"
cyan = "#3a0f12"
white = "#3a0f12"

[colors.bright]
black = "#3a0f12"
red = "#3a0f12"
green = "#3a0f12"
yellow = "#3a0f12"
blue = "#3a0f12"
magenta = "#3a0f12"
cyan = "#3a0f12"
white = "#3a0f12"

[colors.dim]
black = "#3a0f12"
red = "#3a0f12"
green = "#3a0f12"
yellow = "#3a0f12"
blue = "#3a0f12"
magenta = "#3a0f12"
cyan = "#3a0f12"
white = "#3a0f12"
