accent = "#c73a2a"
cursor = "#c73a2a"
foreground = "#3a0f12"
background = "#faede8"
selection_foreground = "#faede8"
selection_background = "#c73a2a"

color0 = "#f3d1cb"
color1 = "#3a0f12"
color2 = "#9f3a32"
color3 = "#a52d24"
color4 = "#e3a19a"
color5 = "#3a0f12"
color6 = "#9f3a32"
color7 = "#3a0f12"
color8 = "#e3a19a"
color9 = "#3a0f12"
color10 = "#9f3a32"
color11 = "#a52d24"
color12 = "#e3695b"
color13 = "#3a0f12"
color14 = "#9f3a32"
color15 = "#3a0f12"
