accent = "#2f1f17"
cursor = "#2f1f17"
foreground = "#2f1f17"
background = "#f5e9df"
selection_foreground = "#f5e9df"
selection_background = "#8f4a2b"

color0 = "#ead7c8"
color1 = "#2f1f17"
color2 = "#6b4331"
color3 = "#9b5a36"
color4 = "#d9b39d"
color5 = "#2f1f17"
color6 = "#6b4331"
color7 = "#2f1f17"
color8 = "#d9b39d"
color9 = "#2f1f17"
color10 = "#6b4331"
color11 = "#9b5a36"
color12 = "#bc7449"
color13 = "#2f1f17"
color14 = "#6b4331"
color15 = "#2f1f17"
