accent = "#e95420"
cursor = "#e95420"
foreground = "#2c001e"
background = "#faede8"
selection_foreground = "#faede8"
selection_background = "#e95420"

color0 = "#f3d6c8"
color1 = "#2c001e"
color2 = "#b24c24"
color3 = "#c34113"
color4 = "#e6b29b"
color5 = "#2c001e"
color6 = "#b24c24"
color7 = "#2c001e"
color8 = "#e6b29b"
color9 = "#2c001e"
color10 = "#b24c24"
color11 = "#c34113"
color12 = "#ff7b54"
color13 = "#2c001e"
color14 = "#b24c24"
color15 = "#2c001e"
