$activeBorderColor = rgba(c73a2aff)
$inactiveBorderColor = rgba(a52d24ee)

general {
    gaps_out = 0
    border_size = 0
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
