$activeBorderColor = rgba(2f1f17ff)
$inactiveBorderColor = rgba(9b5a36ee)

general {
    gaps_out = 0
    border_size = 0
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
