set -g status-style "bg=default,fg=#b24c24"
set -g status-left "#[fg=#2c001e,bg=#e6b29b,bold] #S #[fg=#b24c24,bg=default] "
set -g status-right "#[fg=#c34113]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#b24c24]#h "
set -g window-status-format "#[fg=#c34113] #I:#W "
set -g window-status-current-format "#[fg=#2c001e,bg=#e6b29b,bold] #I:#W #[fg=#b24c24,bg=default]"
set -g pane-border-style "fg=#c34113"
set -g pane-active-border-style "fg=#2c001e"
set -g message-style "bg=#f3d6c8,fg=#2c001e"
set -g message-command-style "bg=#f3d6c8,fg=#2c001e"
set -g mode-style "bg=#e6b29b,fg=#2c001e"
set -g popup-style "bg=#f3d6c8,fg=#2c001e"
set -g popup-border-style "fg=#c34113,bg=#f3d6c8"
set -g menu-style "bg=#f3d6c8,fg=#2c001e"
set -g menu-selected-style "bg=#e6b29b,fg=#2c001e"
setw -g clock-mode-colour "#c34113"
